from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
import os
import logging
from datetime import datetime
 
logger = logging.getLogger(__name__)
 
 
def create_report(filename, summary, risk):
    """
    Create a PDF report for a meeting
    
    Args:
        filename: Original audio filename
        summary: Meeting summary text
        risk: Risk analysis text
        
    Returns:
        True if successful, False otherwise
    """
    try:
        # Ensure reports directory exists
        os.makedirs("reports", exist_ok=True)
        
        # Generate report filename
        name = os.path.splitext(
    os.path.basename(filename)
)[0]
        pdf_path = f"reports/{name}.pdf"
        
        logger.info(f"Creating report: {pdf_path}")
        
        # Create PDF document
        pdf = SimpleDocTemplate(
            pdf_path,
            title="AI Meeting Report",
            author="AI Meeting-to-Execution Agent",
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch
        )
        
        # Define styles
        styles = getSampleStyleSheet()
        
        # Create custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=30,
            alignment=1  # Center
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#333333'),
            spaceBefore=12,
            spaceAfter=12,
            borderColor=colors.HexColor('#CCCCCC'),
            borderPadding=10,
            borderRadius=3
        )
        
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['BodyText'],
            fontSize=11,
            leading=16,
            alignment=4  # Justify
        )
        
        # Build document content
        content = []
        
        # Title
        content.append(
            Paragraph("AI Meeting Report", title_style)
        )
        
        # Metadata
        metadata_text = f"<font size=9>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Source: {filename}</font>"
        content.append(
            Paragraph(metadata_text, styles['Normal'])
        )
        
        content.append(Spacer(1, 12))
        
        # Summary Section
        content.append(
            Paragraph("<b>📋 Meeting Summary</b>", heading_style)
        )
        
        # Truncate summary if too long
        if not summary:
            summary = "Summary not available"

        summary_text = (
            summary if len(summary) < 5000
            else summary[:5000] + "..."
        )        
        content.append(
            Paragraph(summary_text, body_style)
        )
        
        content.append(Spacer(1, 20))
        
        # Risk Analysis Section
        content.append(
            Paragraph("<b>⚠️ Risk Analysis</b>", heading_style)
        )
        
        # Truncate risk if too long
        if not risk:
            risk = "Risk analysis not available"

        risk_text = (
            risk if len(risk) < 5000
            else risk[:5000] + "..."
        )        
        content.append(
            Paragraph(risk_text, body_style)
        )
        
        content.append(Spacer(1, 20))
        
        # Footer
        footer_text = "<font size=8><i>This report was automatically generated by the AI Meeting-to-Execution Agent.</i></font>"
        content.append(Spacer(1, 12))
        content.append(Paragraph(footer_text, styles['Normal']))
        
        # Build PDF
        pdf.build(content)
        
        logger.info(f"✅ Report created successfully: {pdf_path}")
        return True
        
    except Exception as e:
        logger.error(f"❌ Failed to create report: {e}", exc_info=True)
        return False